# Generated by Django 5.2.8 on 2025-11-27 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='company_id',
            new_name='reseller_id',
        ),
    ]
