# Generated by Django 5.2.8 on 2025-12-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='access_token',
            field=models.CharField(editable=False, max_length=64, null=True, unique=True),
        ),
    ]
