# Generated by Django 5.2.8 on 2025-12-04 12:46

from django.db import migrations
import secrets

def generate_tokens(apps, schema_editor):
    Booking = apps.get_model('core', 'Booking')
    for booking in Booking.objects.filter(access_token__isnull=True):
        booking.access_token = secrets.token_urlsafe(32)
        booking.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_booking_access_token'),
    ]

    operations = [
        migrations.RunPython(generate_tokens),
    ]
