# Generated by Django 5.2.8 on 2025-11-27 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_create_reseller'),
    ]

    operations = [
        # Rename the integer field to a relation field name
        migrations.RenameField(
            model_name='product',
            old_name='reseller_id',
            new_name='reseller',
        ),
        # Convert the integer field into a ForeignKey to Reseller.
        # This keeps the underlying DB column name as `reseller_id`.
        migrations.AlterField(
            model_name='product',
            name='reseller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reseller'),
        ),
    ]
