# Generated by Django 5.2.8 on 2025-11-27 10:16

from django.db import migrations


def seed_initial_data(apps, schema_editor):
    Reseller = apps.get_model('core', 'Reseller')
    Product = apps.get_model('core', 'Product')

    # Only run this seeding in debug environments
    import os
    if str(os.environ.get('DEBUG', '')).strip() != '1':
        # Skip seeding when DEBUG is not explicitly set to 1
        # Using a simple print because logging may not be configured during migrations
        print('Skipping initial seed: DEBUG env var is not 1')
        return

    from decimal import Decimal
    import random

    # Requirements: at least 50 resellers, each with at least 30 parking spaces
    reseller_count = 50
    products_per_reseller = 30

    # Deterministic mock reseller names to ensure idempotency (50 realistic mock company names)
    reseller_names = [
        "SkyBridge Parking",
        "AeroPark Solutions",
        "Terminal Park Co.",
        "Runway Parking Group",
        "JetSet Parking",
        "BlueSky Parking",
        "CloudNine Parking",
        "Beacon Airport Parking",
        "Gatehouse Parking",
        "Horizon Park & Stay",
        "ParkPort Services",
        "SwiftPark",
        "Airside Parking",
        "Orbit Parking",
        "Skyline Park & Fly",
        "TravelNest Parking",
        "Parkwise Airports",
        "WingSpan Parking",
        "AviaPark",
        "ParkHub Airports",
        "FlyAway Parking",
        "ParkPilot",
        "QuickJet Parking",
        "Metro Airport Parking",
        "CityGate Parking",
        "Harbor Park & Fly",
        "Apex Airport Parking",
        "Pioneer Park & Fly",
        "Summit Airport Parking",
        "PrimeGate Parking",
        "Lighthouse Airport Parking",
        "Sterling Airport Parking",
        "Vista Park & Fly",
        "NorthStar Airport Parking",
        "JetPort Parking",
        "Compass Airport Parking",
        "Liberty Airport Parking",
        "Unity Airport Parking",
        "Nova Airport Parking",
        "Atlas Airport Parking",
        "Titan Airport Parking",
        "Zenith Airport Parking",
        "Platinum Airport Parking",
        "Evergreen Airport Parking",
        "Sapphire Airport Parking",
        "Amber Airport Parking",
        "Coral Airport Parking",
        "Granite Airport Parking",
        "OnTime Airport Parking",
        "ParkLynx Airports",
    ]

    for r_name in reseller_names:
        reseller, _ = Reseller.objects.get_or_create(name=r_name)

        for i in range(1, products_per_reseller + 1):
            # Deterministic name ensures idempotency
            name = f"Parking Space {i}"

            # Random values within required ranges
            price = Decimal(str(random.randint(15, 30)))  # whole number between 15 and 30
            rating = Decimal(str(random.randint(10, 50) / 10))  # 1.0 to 5.0 step 0.1

            Product.objects.get_or_create(
                reseller=reseller,
                name=name,
                defaults={
                    'type': 'parking_space',
                    'price_per_day': price,
                    'rating': rating,
                }
            )


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_product_reseller_fk'),
    ]

    operations = [
        migrations.RunPython(seed_initial_data),
    ]
