# Generated by Django 5.2.8 on 2025-12-04 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_generate_access_tokens'),
        ('core', '0005_alter_booking_access_token_alter_booking_end_date_and_more'),
    ]

    operations = [
    ]
