# Generated by Django 5.2.8 on 2025-12-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20251204_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='access_token',
            field=models.CharField(editable=False, max_length=128, unique=True),
        ),
    ]
